on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: ProyectoFrontKi   # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: ''        # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '20.x'                 # set this to the node version to use

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: node-app
        path: .

  deploy:
    permissions:
      contents: none
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: node-app

    - name: Login to Azure using Service Principal
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_9C368F4C0613483CA9EA25F1BE4B2253 }}
        tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_4861E0B05ACA41859F3D425D34727806 }}
        subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A2AF73659A76468CB003B53AFD012EB6 }}
        client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}  # Add this secret for Service Principal login
        auth-type: 'SERVICE_PRINCIPAL'  # Use SERVICE_PRINCIPAL as auth type

    - name: 'Deploy to Azure WebApp'
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
